name: mayr_flutter_extensions
description: A comprehensive set of handy Flutter-specific extensions to make your Flutter code cleaner, shorter, and more expressive. Works alongside mayr_dart_extensions for complete functionality.
version: 1.0.0
homepage: https://mayrlabs.com
repository: https://github.com/MayR-Labs/mayr_flutter_extensions
issue_tracker: https://github.com/MayR-Labs/mayr_flutter_extensions/issues
documentation: https://github.com/MayR-Labs/mayr_flutter_extensions
license: MIT

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - extensions
  - utilities
  - flutter
  - productivity
  - toolkit
